### ISSUE TITLE
AD识别比赛

### ISSUE THREAD

**Issue by beijita-yegucheng** [THUsatlab/AD2021#3]
亲爱的AD识别比赛组织者您好！
最近我们将官方提供的基线代码（ncmmsc2021_baseline_cnn_pytorch）成功实现运行，但是发现以下问题，首先是程序每次跑的结果不一样，应该是没有设置随机数。还有就是官方公众号中提到基线的测试集分数，我的问题是可不可以提供一下对应的训练时测试的结果，还有模型。
急切的希望的到回复，十分感谢！

**Comment by xuchuchan92** [comment]
你好，第一个问题中每次运行的结果不一样的原因除了随机数问题外，还有一个重要的问题是原始数据存在多个样本的实际病人是同一个，并且在预处理阶段还把同一个wav文件分割成了多个，再加上在train-val分割的时候没有区分病人，导致训练数据和验证数据混在了一起。最终因为随机的混乱的train-val分割，导致每次训练结果差异较大。
解决办法是：在预处理前，人工分好train和val样本，分的时候注意同一病人不能跨train-val数据集，然后分别预处理，然后再用train数据集训练，用val数据集验证。
第二个问题中，参赛方请通过基线的代码训练获得相应的模型；后续会公开测试结果的准确率等指标。
